baseURL = "https://navcoin-knowledge-base.netlify.com/"
theme = "dot"


[params]
primaryColor = "#7243bf"
secondaryColor = "#c0e4fd"
textColor = "#636363"
textColorDark = "#242738"
whiteColor = "#ffffff"

[Languages]

  # English Language
  [Languages.en]
  languageName = "En"
  weight = 1
  languageCode = "en-us"
  title = "NavCoin Knowledge Base"
  dateFormat = "2 January 2006"
  home = "Home"
  logo = "NavCoin Knowledge Base"
  copyright = "Created by the NavCoin Community."

    # navigation
    [Languages.en.menu]
    
      [[Languages.en.menu.main]]
        weight = 2
        name = "Faq"
        url = "/faq"
        
      # [[Languages.en.menu.main]]
        # weight = 2
        # name = "pages"
        # url = "/pages"
        # hasChildren = true

          # [[Languages.en.menu.main]]
          # parent = "pages"
          # name = "Elements"
          # URL = "/elements"
          # weight = 1

          # [[Languages.en.menu.main]]
          # parent = "pages"
          # name = "Installation"
          # URL = "/installation"
          # weight = 2




    # banner
    [Languages.en.params.banner]
      title = "NavCoin Knowledge base"
      description = "Find advice and answers from the NavCoin community"
      image = "images/banner.jpg"
      placeholder = "Have a question? Just ask here or enter terms"

    # Topics
    [Languages.en.params.topics]
      title = "Find your answer by subject"
    
    # call to action
    [Languages.en.params.cta]
      enable = true
      title = "Didn't find an answer to your question?"
      description = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
      btnText = "contact us"
      btnURL = "/contact"

    # contact
    [Languages.en.params.contact]
      title = "Got Any Questions"
      content = "Visit the NavCoin discord to talk to the community: ."

    # footer social icon
    [[Languages.en.socialIcon]]
      icon = "fab fa-facebook-f"
      URL = "https://www.facebook.com/NavCoin/"

    [[Languages.en.socialIcon]]
      icon = "fab fa-twitter"
      URL = "https://twitter.com/NavCoin"
      
    [[Languages.en.socialIcon]]
      icon = "fab fa-discord"
      URL = "https://discord.gg/y4Vu9jw"
      
    [[Languages.en.socialIcon]]
      icon = "fab fa-medium-m"
      URL = "http://medium.com/nav-coin"



